language: ruby
os: osx
osx_image: xcode9

before_install: brew update
script: brew install --force --build-bottle ./hhvm.rb --verbose
after_success: brew bottle --force-core-tap hhvm --verbose

addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
      - hhvm-*
